package com.idunnololz.tools

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import retrofit2.Call
import retrofit2.Retrofit
import retrofit2.converter.kotlinx.serialization.asConverterFactory
import retrofit2.http.GET
import retrofit2.http.HeaderMap
import retrofit2.http.QueryMap
import java.io.File


object UpdateInstanceData {

  @JvmStatic
  fun main(args: Array<String>) {
    val retrofit = Retrofit.Builder()
      .baseUrl("https://data.lemmyverse.net/")
      .addConverterFactory(json.asConverterFactory("application/json".toMediaType()))
      .build()

    val api: LemmyVerseApi = retrofit.create<LemmyVerseApi>(LemmyVerseApi::class.java)

    val instanceStats = api.instanceStats(mapOf(), mapOf()).execute().body()

    val topInstances = instanceStats?.sortedByDescending { it.counts.usersActiveMonth }
      ?.take(50)
      ?: listOf()

    topInstances.forEach {
      println("${it.baseurl} - ${it.counts.usersActiveMonth}")
    }

    val instancesFile = File("app/src/main/java/com/idunnololz/summit/util/consts/LemmyInstances.kt")
    instancesFile.parentFile.mkdirs()
    instancesFile.outputStream().bufferedWriter().use {
      it.appendLine("package com.idunnololz.summit.util.consts")
      it.appendLine()

      it.appendLine("// DO NOT MODIFIED")
      it.appendLine("// THIS FILE IS AUTOGENERATED")

      it.appendLine("val LEMMY_INSTANCES = listOf(")
      topInstances.forEach { instance ->
        it.appendLine("  \"${instance.baseurl}\",")
      }
      it.appendLine(")")
    }
  }

  private val json: Json by lazy {
    Json {
      ignoreUnknownKeys = true
      isLenient = true
      explicitNulls = false
    }
  }
}

/*
  {
    "baseurl": "lemmy.k2pk.com",
    "url": "https://lemmy.k2pk.com/",
    "name": "K2PK Lemmyverse",
    "desc": "A multiverse of all kinds of content",
    "downvotes": true,
    "nsfw": false,
    "create_admin": false,
    "private": false,
    "reg_mode": 2,
    "fed": true,
    "version": "0.19.15",
    "open": true,

    "usage": {
      "users": {
        "total": 8,
        "activeHalfyear": 2,
        "activeMonth": 1
      },
      "localPosts": 7,
      "localComments": 1
    },
    "counts": {
      "site_id": 1,
      "users": 8,
      "posts": 7,
      "comments": 1,
      "communities": 10,
      "users_active_day": 0,
      "users_active_week": 1,
      "users_active_month": 1,
      "users_active_half_year": 2
    },
    "icon": "https://lemmy.k2pk.com/pictrs/image/2090ab48-e658-493d-aae3-fc619797d6f2.png",
    "banner": "https://lemmy.k2pk.com/pictrs/image/85235f4d-eac6-419c-8e02-bbb827a982cf.png",
    "langs": [
      "en"
    ],
    "date": "2025-04-16T02:27:57.623250Z",
    "published": 1744770477000,
    "time": 1771681577903,
    "score": 0.3085,
    "isSuspicious": false,
    "metrics": {
      "usersTotal": 8,
      "usersMonth": 1,
      "usersWeek": 1,
      "totalActivity": 8,
      "localPosts": 7,
      "localComments": 1,
      "averageUsers": 6,
      "biggestJump": 1,
      "averagePerMinute": 0.00004,
      "userActivityScore": 1,
      "activityUserScore": 1,
      "userActiveMonthScore": 8
    },
    "tags": [
      "cloudflare"
    ],
    "susReason": [],
    "trust": {
      "lastCrawled": 1771681577903,
      "baseurl": "lemmy.k2pk.com",
      "metrics": {
        "usersTotal": 8,
        "usersMonth": 1,
        "usersWeek": 1,
        "totalActivity": 8,
        "localPosts": 7,
        "localComments": 1,
        "averageUsers": 6,
        "biggestJump": 1,
        "averagePerMinute": 0.00004,
        "userActivityScore": 1,
        "activityUserScore": 1,
        "userActiveMonthScore": 8
      },
      "users": 8,
      "name": "K2PK Lemmyverse",
      "base": "lemmy.k2pk.com",
      "actor_id": "https://lemmy.k2pk.com/",
      "tags": [
        "cloudflare"
      ],
      "endorsements": 0,
      "censure_reasons": null,
      "flags": [],
      "score": 0.3085,
      "reasons": []
    },
    "blocks": {
      "incoming": 0,
      "outgoing": 0
    },
    "blocked": [],
    "admins": [
      "https://lemmy.k2pk.com/u/b166ir"
    ]
  }
 */

@Serializable
class InstanceStat(
  val baseurl: String,
  val url: String,
  val name: String,
  val desc: String,
  val downvotes: Boolean,
  val nsfw: Boolean,
  @SerialName("create_admin")
  val createAdmin: Boolean,
  val private: Boolean,
  @SerialName("reg_mode")
  val regMode: Int,
  val fed: Boolean,
  val version: String,
  val open: Boolean,
  val counts: InstanceCounts,
)

@Serializable
class InstanceCounts(
  @SerialName("site_id")
  val siteId: Int,
  val users: Int,
  val posts: Int,
  val comments: Int,
  val communities: Int,
  @SerialName("users_active_day")
  val usersActiveDay: Int,
  @SerialName("users_active_week")
  val usersActiveWeek: Int,
  @SerialName("users_active_month")
  val usersActiveMonth: Int,
  @SerialName("users_active_half_year")
  val usersActiveHalfYear: Int,
)

interface LemmyVerseApi {

  @GET("data/instance.full.json")
  fun instanceStats(
    @HeaderMap headers: Map<String, String>,
    @QueryMap form: Map<String, String>,
  ): Call<List<InstanceStat>>

}