/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param communityId
 * @param personId
 * @param added
 */

data class AddModToCommunity(

  @SerializedName("community_id")
  val communityId: kotlin.Int,

  @SerializedName("person_id")
  val personId: kotlin.Int,

  @SerializedName("added")
  val added: kotlin.Boolean,

)
