/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param instanceId
 * @param block
 */

data class BlockInstance(

  @SerializedName("instance_id")
  val instanceId: kotlin.Int,

  @SerializedName("block")
  val block: kotlin.Boolean,

)
