/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.CommunityView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param communityView 
 * @param blocked 
 */


data class BlockCommunityResponse (

    @SerializedName("community_view")
    val communityView: CommunityView,

    @SerializedName("blocked")
    val blocked: kotlin.Boolean

) {


}

