/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.Community
import com.idunnololz.summit.api.dto.piefed.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param community 
 * @param person 
 */


data class CommunityBlockView (

    @SerializedName("community")
    val community: Community,

    @SerializedName("person")
    val person: Person

) {


}

