/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param recipientId 
 * @param commentId 
 * @param read 
 * @param published 
 */


data class CommentReply (

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("recipient_id")
    val recipientId: kotlin.Int,

    @SerializedName("comment_id")
    val commentId: kotlin.Int,

    @SerializedName("read")
    val read: kotlin.Boolean,

    @SerializedName("published")
    val published: java.time.OffsetDateTime

) {


}

