/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param reason
 * @param expiredAt
 * @param community
 * @param bannedUser
 * @param bannedBy
 * @param expired
 */

data class CommunityModerationBanItem(

  @SerializedName("reason")
  val reason: kotlin.String? = null,

  @SerializedName("expiredAt")
  val expiredAt: kotlin.String? = null,

  @SerializedName("community")
  val community: CommunityView? = null,

  @SerializedName("bannedUser")
  val bannedUser: Person? = null,

  @SerializedName("bannedBy")
  val bannedBy: Person? = null,

  @SerializedName("expired")
  val expired: kotlin.Boolean? = null,

)
