/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param commentReport
 * @param comment
 * @param post
 * @param community
 * @param creator
 * @param commentCreator
 * @param counts
 * @param creatorBannedFromCommunity
 * @param creatorIsModerator
 * @param creatorIsAdmin
 * @param creatorBlocked
 * @param subscribed
 * @param saved
 * @param myVote
 * @param resolver
 */

data class CommentReportView(

  @SerializedName("comment_report")
  val commentReport: CommentReport,

  @SerializedName("comment")
  val comment: Comment,

  @SerializedName("post")
  val post: Post,

  @SerializedName("community")
  val community: Community,

  @SerializedName("creator")
  val creator: Person,

  @SerializedName("comment_creator")
  val commentCreator: Person,

  @SerializedName("counts")
  val counts: CommentAggregates,

  @SerializedName("creator_banned_from_community")
  val creatorBannedFromCommunity: kotlin.Boolean,

  @SerializedName("creator_is_moderator")
  val creatorIsModerator: kotlin.Boolean,

  @SerializedName("creator_is_admin")
  val creatorIsAdmin: kotlin.Boolean,

  @SerializedName("creator_blocked")
  val creatorBlocked: kotlin.Boolean,

  @SerializedName("subscribed")
  val subscribed: SubscribedType,

  @SerializedName("saved")
  val saved: kotlin.Boolean,

  @SerializedName("my_vote")
  val myVote: kotlin.Int? = null,

  @SerializedName("resolver")
  val resolver: Person? = null,

)
