/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentId 
 * @param score 
 * @param upvotes 
 * @param downvotes 
 * @param published 
 * @param childCount 
 */


data class CommentAggregates (

    @SerializedName("comment_id")
    val commentId: kotlin.Int,

    @SerializedName("score")
    val score: kotlin.Int,

    @SerializedName("upvotes")
    val upvotes: kotlin.Int,

    @SerializedName("downvotes")
    val downvotes: kotlin.Int,

    @SerializedName("published")
    val published: String,

    @SerializedName("child_count")
    val childCount: kotlin.Int

) {


}

