/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param body
 * @param postId
 * @param parentId
 * @param languageId
 */

data class CreateComment(

  @SerializedName("body")
  val body: kotlin.String,

  @SerializedName("post_id")
  val postId: kotlin.Int,

  @SerializedName("parent_id")
  val parentId: kotlin.Int? = null,

  @SerializedName("language_id")
  val languageId: kotlin.Int? = null,

)
