/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentId 
 * @param deleted 
 */


data class DeleteComment (

    @SerializedName("comment_id")
    val commentId: kotlin.Int,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean

) {


}

