/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.PostFeatureType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param postId 
 * @param featured 
 * @param featureType 
 */


data class FeaturePost (

    @SerializedName("post_id")
    val postId: kotlin.Int,

    @SerializedName("featured")
    val featured: kotlin.Boolean,

    @SerializedName("feature_type")
    val featureType: PostFeatureType

) {


}

