/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param communityId
 * @param follow
 */

data class FollowCommunity(

  @SerializedName("community_id")
  val communityId: kotlin.Int,

  @SerializedName("follow")
  val follow: kotlin.Boolean,

)
