/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param postView
 * @param communityView
 * @param moderators
 * @param crossPosts
 */

data class GetPostResponse(

  @SerializedName("post_view")
  val postView: PostView,

  @SerializedName("community_view")
  val communityView: CommunityView,

  @SerializedName("moderators")
  val moderators: kotlin.collections.List<CommunityModeratorView>,

  @SerializedName("cross_posts")
  val crossPosts: kotlin.collections.List<PostView>,

)
