/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param personId
 * @param username
 * @param sort
 * @param page
 * @param limit
 * @param communityId
 * @param savedOnly
 * @param includeContent
 */

data class GetPersonDetails(

  @SerializedName("person_id")
  val personId: kotlin.Int? = null,

  @SerializedName("username")
  val username: kotlin.String? = null,

  @SerializedName("sort")
  val sort: SortType? = null,

  @SerializedName("page")
  val page: kotlin.Int? = null,

  @SerializedName("limit")
  val limit: kotlin.Int? = null,

  @SerializedName("community_id")
  val communityId: kotlin.Int? = null,

  @SerializedName("saved_only")
  val savedOnly: kotlin.Boolean? = null,

  @SerializedName("include_content")
  val includeContent: kotlin.Boolean? = null,

)
