/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.ListingType
import com.idunnololz.summit.api.dto.piefed.SortType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param sort 
 * @param pageCursor 
 * @param limit 
 * @param communityId 
 * @param personId 
 * @param communityName 
 * @param likedOnly 
 * @param savedOnly 
 */


data class GetPosts (

    @SerializedName("type_")
    val type: ListingType? = null,

    @SerializedName("sort")
    val sort: SortType? = null,

    @SerializedName("page_cursor")
    val pageCursor: kotlin.Int? = null,

    @SerializedName("limit")
    val limit: kotlin.Int? = null,

    @SerializedName("community_id")
    val communityId: kotlin.Int? = null,

    @SerializedName("person_id")
    val personId: kotlin.Int? = null,

    @SerializedName("community_name")
    val communityName: kotlin.String? = null,

    @SerializedName("liked_only")
    val likedOnly: kotlin.Boolean? = null,

    @SerializedName("saved_only")
    val savedOnly: kotlin.Boolean? = null

) {


}

