/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param unreadOnly 
 * @param page 
 * @param limit 
 */


data class GetPrivateMessages (

    @SerializedName("unread_only")
    val unreadOnly: kotlin.Boolean? = null,

    @SerializedName("page")
    val page: kotlin.Int? = null,

    @SerializedName("limit")
    val limit: kotlin.Int? = null

) {


}

