/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param personId
 * @param page
 * @param limit
 */

data class GetPrivateMessagesConversation(

  @SerializedName("person_id")
  val personId: kotlin.Int,

  @SerializedName("page")
  val page: kotlin.Int? = null,

  @SerializedName("limit")
  val limit: kotlin.Int? = null,

)
