/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param site
 * @param version
 * @param admins
 * @param myUser
 */

data class GetSiteResponse(

  @SerializedName("site")
  val site: Site,

  @SerializedName("version")
  val version: kotlin.String,

  @SerializedName("admins")
  val admins: kotlin.collections.List<PersonView>,

  @SerializedName("my_user")
  val myUser: MyUserInfo? = null,

)
