/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param replies 
 * @param mentions 
 * @param privateMessages 
 */


data class GetUnreadCountResponse (

    @SerializedName("replies")
    val replies: kotlin.Int,

    @SerializedName("mentions")
    val mentions: kotlin.Int,

    @SerializedName("private_messages")
    val privateMessages: kotlin.Int

) {


}

