/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param domain
 * @param published
 * @param updated
 * @param software
 * @param version
 */

data class InstanceWithoutFederationState(

  @SerializedName("id")
  val id: kotlin.Int,

  @SerializedName("domain")
  val domain: kotlin.String,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("updated")
  val updated: kotlin.String? = null,

  @SerializedName("software")
  val software: kotlin.String? = null,

  @SerializedName("version")
  val version: kotlin.String? = null,

)
