/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param counts
 * @param localUser
 * @param person
 */

data class LocalUserView(

  @SerializedName("counts")
  val counts: PersonAggregates,

  @SerializedName("local_user")
  val localUser: LocalUser,

  @SerializedName("person")
  val person: Person,

)
