/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentReplyId 
 * @param read 
 */


data class MarkReplyAsRead (

    @SerializedName("comment_reply_id")
    val commentReplyId: kotlin.Int,

    @SerializedName("read")
    val read: kotlin.Boolean

) {


}

