/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param communityId 
 * @param userId 
 * @param reason 
 * @param expiredAt 
 */


data class ModerateCommunityBan (

    @SerializedName("community_id")
    val communityId: kotlin.Int,

    @SerializedName("user_id")
    val userId: kotlin.Int,

    @SerializedName("reason")
    val reason: kotlin.String,

    @SerializedName("expiredAt")
    val expiredAt: kotlin.String

) {


}

