/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param newNotifications
 * @param readNotifications
 * @param totalNotifications
 */

data class NotificationsCountsView(

  @SerializedName("new_notifications")
  val newNotifications: kotlin.Int,

  @SerializedName("read_notifications")
  val readNotifications: kotlin.Int,

  @SerializedName("total_notifications")
  val totalNotifications: kotlin.Int? = null,

)
