/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param counts
 * @param items
 * @param status
 * @param user
 */

data class NotificationsResponse(

  @SerializedName("counts")
  val counts: NotificationsCountsView,

  @SerializedName("items")
  val items: kotlin.collections.List<NotificationsResponseItemsInner>,

  @SerializedName("status")
  val status: kotlin.String,

  @SerializedName("user")
  val user: kotlin.String,

)
