/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param person 
 * @param target 
 */


data class PersonBlockView (

    @SerializedName("person")
    val person: Person,

    @SerializedName("target")
    val target: Person

) {


}

