/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.PersonView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param personView 
 */


data class PersonResponse (

    @SerializedName("person_view")
    val personView: PersonView

) {


}

