/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentCount 
 * @param personId 
 * @param postCount 
 */


data class PersonAggregates (

    @SerializedName("comment_count")
    val commentCount: kotlin.Int,

    @SerializedName("person_id")
    val personId: kotlin.Int,

    @SerializedName("post_count")
    val postCount: kotlin.Int

) {


}

