/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param person
 * @param counts
 * @param isAdmin
 * @param activityAlert
 */

data class PersonView(

  @SerializedName("person")
  val person: Person,

  @SerializedName("counts")
  val counts: PersonAggregates,

  @SerializedName("is_admin")
  val isAdmin: kotlin.Boolean,

  @SerializedName("activity_alert")
  val activityAlert: kotlin.Boolean,

)
