/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.PrivateMessageView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param privateMessages 
 */


data class PrivateMessagesResponse (

    @SerializedName("private_messages")
    val privateMessages: kotlin.collections.List<PrivateMessageView>

) {


}

