/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.PrivateMessageView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param privateMessageView 
 */


data class PrivateMessageResponse (

    @SerializedName("private_message_view")
    val privateMessageView: PrivateMessageView

) {


}

