/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed

import com.idunnololz.summit.api.dto.piefed.Person
import com.idunnololz.summit.api.dto.piefed.PrivateMessage

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param privateMessage 
 * @param creator 
 * @param recipient 
 */


data class PrivateMessageView (

    @SerializedName("private_message")
    val privateMessage: PrivateMessage,

    @SerializedName("creator")
    val creator: Person,

    @SerializedName("recipient")
    val recipient: Person

) {


}

