/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param comment
 * @param post
 * @param community
 * @param person
 */

data class ResolveObjectResponse(

  @SerializedName("comment")
  val comment: CommentView? = null,

  @SerializedName("post")
  val post: PostView? = null,

  @SerializedName("community")
  val community: CommunityView? = null,

  @SerializedName("person")
  val person: PersonView? = null,

)
