/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param q
 * @param type
 * @param sort
 * @param listingType
 * @param page
 * @param limit
 */

data class Search(

  @SerializedName("q")
  val q: kotlin.String,

  @SerializedName("type_")
  val type: SearchType? = null,

  @SerializedName("sort")
  val sort: SortType? = null,

  @SerializedName("listing_type")
  val listingType: ListingType? = null,

  @SerializedName("page")
  val page: kotlin.Int? = null,

  @SerializedName("limit")
  val limit: kotlin.Int? = null,

)
