/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.AdminPurgeComment
import com.idunnololz.summit.api.dto.piefed.models.Person
import com.idunnololz.summit.api.dto.piefed.models.Post

/**
 *
 *
 * @param adminPurgeComment
 * @param post
 * @param admin
 */

data class AdminPurgeCommentView(

  @SerializedName("admin_purge_comment")
  val adminPurgeComment: AdminPurgeComment,

  @SerializedName("post")
  val post: Post,

  @SerializedName("admin")
  val admin: Person? = null,

)
