/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.AdminPurgePerson
import com.idunnololz.summit.api.dto.piefed.models.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param adminPurgePerson 
 * @param admin 
 */


data class AdminPurgePersonView (

    @SerializedName("admin_purge_person")
    val adminPurgePerson: AdminPurgePerson,

    @SerializedName("admin")
    val admin: Person? = null

) {


}

