/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param png
 * @param wav
 * @param uuid
 */

data class CaptchaFields(

  @SerializedName("png")
  val png: kotlin.String? = null,

  @SerializedName("wav")
  val wav: kotlin.String? = null,

  @SerializedName("uuid")
  val uuid: kotlin.String? = null,

)
