/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param postCount
 * @param postReplyCount
 * @param published
 * @param subscriptionsCount
 * @param totalSubscriptionsCount
 * @param activeDaily
 * @param activeWeekly
 * @param activeMonthly
 * @param active6monthly
 */

data class CommunityAggregates(

  @SerializedName("id")
  val id: kotlin.Int,

  @SerializedName("post_count")
  val postCount: kotlin.Int,

  @SerializedName("post_reply_count")
  val postReplyCount: kotlin.Int,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("subscriptions_count")
  val subscriptionsCount: kotlin.Int,

  @SerializedName("total_subscriptions_count")
  val totalSubscriptionsCount: kotlin.Int,

  @SerializedName("active_daily")
  val activeDaily: kotlin.Int? = null,

  @SerializedName("active_weekly")
  val activeWeekly: kotlin.Int? = null,

  @SerializedName("active_monthly")
  val activeMonthly: kotlin.Int? = null,

  @SerializedName("active_6monthly")
  val active6monthly: kotlin.Int? = null,

)
