/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param communityId 
 * @param reason 
 * @param userId 
 * @param expiresAt 
 * @param permanent 
 */


data class CommunityModerationBanRequest (

    @SerializedName("community_id")
    val communityId: kotlin.Int,

    @SerializedName("reason")
    val reason: kotlin.String,

    @SerializedName("user_id")
    val userId: kotlin.Int,

    @SerializedName("expires_at")
    val expiresAt: kotlin.String? = null,

    @SerializedName("permanent")
    val permanent: kotlin.Boolean? = null

) {


}

