/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param flairId
 * @param flairTitle
 * @param textColor Hex color code for the text of the flair.
 * @param backgroundColor Hex color code for the background of the flair.
 * @param blurImages
 */

data class CommunityFlairEditRequest(

  @SerializedName("flair_id")
  val flairId: kotlin.Int,

  @SerializedName("flair_title")
  val flairTitle: kotlin.String? = null,

  /* Hex color code for the text of the flair. */
  @SerializedName("text_color")
  val textColor: kotlin.String? = null,

  /* Hex color code for the background of the flair. */
  @SerializedName("background_color")
  val backgroundColor: kotlin.String? = null,

  @SerializedName("blur_images")
  val blurImages: kotlin.Boolean? = null,

)
