/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param commentId
 * @param published
 * @param read
 * @param recipientId
 */

data class CommentReply(

  @SerializedName("id")
  val id: kotlin.Int,

  @SerializedName("comment_id")
  val commentId: kotlin.Int,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("read")
  val read: kotlin.Boolean,

  @SerializedName("recipient_id")
  val recipientId: kotlin.Int,

)
