/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param postId
 * @param nsfwStatus
 */

data class CommunityModerationNsfwRequest(

  @SerializedName("post_id")
  val postId: kotlin.Int,

  @SerializedName("nsfw_status")
  val nsfwStatus: kotlin.Boolean,

)
