/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param childCount
 * @param commentId
 * @param downvotes
 * @param published
 * @param score
 * @param upvotes
 */

data class CommentAggregates(

  @SerializedName("child_count")
  val childCount: kotlin.Int,

  @SerializedName("comment_id")
  val commentId: kotlin.Int,

  @SerializedName("downvotes")
  val downvotes: kotlin.Int,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("score")
  val score: kotlin.Int,

  @SerializedName("upvotes")
  val upvotes: kotlin.Int,

)
