/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.CommunityView

/**
 *
 *
 * @param communityView
 * @param discussionLanguages
 */

data class CommunityResponse(

  @SerializedName("community_view")
  val communityView: CommunityView,

  @SerializedName("discussion_languages")
  val discussionLanguages: kotlin.collections.List<kotlin.Int>,

)
