/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.Person

/**
 *
 *
 * @param id
 * @param creatorId
 * @param published
 * @param updated
 * @param members
 */

data class ConversationInfoView(

  @SerializedName("id")
  val id: kotlin.Int,

  @SerializedName("creator_id")
  val creatorId: kotlin.Int,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("updated")
  val updated: kotlin.String,

  @SerializedName("members")
  val members: kotlin.collections.List<Person>? = null,

)
