/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param creatorId User id of the reporter
 * @param conversationId
 * @param reason
 * @param description Any other additional information provided by the reporter
 * @param resolved
 * @param published
 */

data class ConversationReport(

  @SerializedName("id")
  val id: kotlin.Int,

  /* User id of the reporter */
  @SerializedName("creator_id")
  val creatorId: kotlin.Int,

  @SerializedName("conversation_id")
  val conversationId: kotlin.Int,

  @SerializedName("reason")
  val reason: kotlin.String?,

  /* Any other additional information provided by the reporter */
  @SerializedName("description")
  val description: kotlin.String?,

  @SerializedName("resolved")
  val resolved: kotlin.Boolean,

  @SerializedName("published")
  val published: kotlin.String,

)
