/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.ConversationInfoView
import com.idunnololz.summit.api.dto.piefed.models.ConversationReport
import com.idunnololz.summit.api.dto.piefed.models.Person
import com.idunnololz.summit.api.dto.piefed.models.PrivateMessageView

/**
 *
 *
 * @param conversationReport
 * @param conversationInformation
 * @param creator
 * @param messageHistory
 */

data class ConversationReportView(

  @SerializedName("conversation_report")
  val conversationReport: ConversationReport,

  @SerializedName("conversation_information")
  val conversationInformation: ConversationInfoView,

  @SerializedName("creator")
  val creator: Person,

  @SerializedName("message_history")
  val messageHistory: kotlin.collections.List<PrivateMessageView>? = null,

)
