/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param content
 * @param recipientId
 */

data class CreatePrivateMessageRequest(

  @SerializedName("content")
  val content: kotlin.String,

  @SerializedName("recipient_id")
  val recipientId: kotlin.Int,

)
