/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param block 
 * @param domain 
 */


data class DomainBlockRequest (

    @SerializedName("block")
    val block: kotlin.Boolean,

    @SerializedName("domain")
    val domain: kotlin.String

) {


}

