/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param body
 * @param commentId
 * @param languageId
 * @param distinguished Visibly mark reply as from a moderator in the web UI
 */

data class EditCommentRequest(

  @SerializedName("body")
  val body: kotlin.String,

  @SerializedName("comment_id")
  val commentId: kotlin.Int,

  @SerializedName("language_id")
  val languageId: kotlin.Int? = null,

  /* Visibly mark reply as from a moderator in the web UI */
  @SerializedName("distinguished")
  val distinguished: kotlin.Boolean? = false,

)
