/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param feedId 
 * @param url URL-safe name/slug for the feed
 * @param title 
 * @param description 
 * @param iconUrl 
 * @param bannerUrl 
 * @param nsfw 
 * @param nsfl 
 * @param `public` 
 * @param communities Newline-separated list of community ap_ids; omit to keep existing communities
 * @param isInstanceFeed 
 * @param showChildPosts 
 * @param parentFeedId 
 */


data class EditFeedRequest (

    @SerializedName("feed_id")
    val feedId: kotlin.Int,

    /* URL-safe name/slug for the feed */
    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("icon_url")
    val iconUrl: kotlin.String? = null,

    @SerializedName("banner_url")
    val bannerUrl: kotlin.String? = null,

    @SerializedName("nsfw")
    val nsfw: kotlin.Boolean? = null,

    @SerializedName("nsfl")
    val nsfl: kotlin.Boolean? = null,

    @SerializedName("public")
    val `public`: kotlin.Boolean? = null,

    /* Newline-separated list of community ap_ids; omit to keep existing communities */
    @SerializedName("communities")
    val communities: kotlin.String? = null,

    @SerializedName("is_instance_feed")
    val isInstanceFeed: kotlin.Boolean? = null,

    @SerializedName("show_child_posts")
    val showChildPosts: kotlin.Boolean? = null,

    @SerializedName("parent_feed_id")
    val parentFeedId: kotlin.Int? = null

) {


}

