/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param privateMessageId
 * @param content
 */

data class EditPrivateMessageRequest(

  @SerializedName("private_message_id")
  val privateMessageId: kotlin.Int,

  @SerializedName("content")
  val content: kotlin.String,

)
