/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param code Error code
 * @param status Error name
 * @param message Error message
 * @param errors Errors
 */

data class Error(

  /* Error code */
  @SerializedName("code")
  val code: kotlin.Int? = null,

  /* Error name */
  @SerializedName("status")
  val status: kotlin.String? = null,

  /* Error message */
  @SerializedName("message")
  val message: kotlin.String? = null,

  /* Errors */
  @SerializedName("errors")
  val errors: kotlin.Any? = null,

) : kotlin.collections.HashMap<String, kotlin.Any>()
