/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.FeedView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param feeds 
 */


data class FeedListResponse (

    @SerializedName("feeds")
    val feeds: kotlin.collections.List<FeedView>

) {


}

