/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param feedId 
 * @param follow 
 */


data class FollowFeedRequest (

    @SerializedName("feed_id")
    val feedId: kotlin.Int,

    @SerializedName("follow")
    val follow: kotlin.Boolean

) {


}

