/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.CommentView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentView 
 */


data class GetCommentResponse (

    @SerializedName("comment_view")
    val commentView: CommentView

) {


}

