/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.CommentReportView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentReportView 
 */


data class GetCommentReportResponse (

    @SerializedName("comment_report_view")
    val commentReportView: CommentReportView

) {


}

