/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.PostReplyView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param comments 
 * @param nextPage 
 */


data class GetPostRepliesResponse (

    @SerializedName("comments")
    val comments: kotlin.collections.List<PostReplyView>? = null,

    @SerializedName("next_page")
    val nextPage: kotlin.String? = null

) {


}

