/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.PrivateMessageReportView

/**
 *
 *
 * @param privateMessageReports
 * @param nextPage
 */

data class GetPrivateMessageReportListResponse(

  @SerializedName("private_message_reports")
  val privateMessageReports: kotlin.collections.List<PrivateMessageReportView>,

  @SerializedName("next_page")
  val nextPage: kotlin.String? = null,

)
