/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.Instance
import com.idunnololz.summit.api.dto.piefed.models.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param instance 
 * @param person 
 */


data class InstanceBlockView (

    @SerializedName("instance")
    val instance: Instance,

    @SerializedName("person")
    val person: Person

) {


}

