/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param domain 
 * @param id 
 * @param published 
 * @param software 
 * @param updated 
 * @param version 
 */


data class Instance (

    @SerializedName("domain")
    val domain: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("published")
    val published: kotlin.String,

    @SerializedName("software")
    val software: kotlin.String? = null,

    @SerializedName("updated")
    val updated: kotlin.String? = null,

    @SerializedName("version")
    val version: kotlin.String? = null

) {


}

