/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.CommentLikeView

/**
 *
 *
 * @param commentLikes
 * @param nextPage
 */

data class ListCommentLikesResponse(

  @SerializedName("comment_likes")
  val commentLikes: kotlin.collections.List<CommentLikeView>,

  @SerializedName("next_page")
  val nextPage: kotlin.String? = null,

)
