/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.PostLikeView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param postLikes 
 * @param nextPage 
 */


data class ListPostLikesResponse (

    @SerializedName("post_likes")
    val postLikes: kotlin.collections.List<PostLikeView>,

    @SerializedName("next_page")
    val nextPage: kotlin.String? = null

) {


}

