/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentReplyId 
 * @param answer 
 */


data class MarkCommentAsAnswerRequest (

    @SerializedName("comment_reply_id")
    val commentReplyId: kotlin.Int,

    @SerializedName("answer")
    val answer: kotlin.Boolean

) {


}

