/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param commentReplyId
 * @param distinguished
 */

data class MarkCommentAsDistinguishedRequest(

  @SerializedName("comment_reply_id")
  val commentReplyId: kotlin.Int,

  @SerializedName("distinguished")
  val distinguished: kotlin.Boolean,

)
