/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url 
 * @param name 
 */


data class MediaView (

    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

