/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param postId
 * @param replyCount
 * @param communityName
 */

data class MiniCrossPosts(

  @SerializedName("post_id")
  val postId: kotlin.Int? = null,

  @SerializedName("reply_count")
  val replyCount: kotlin.Int? = null,

  @SerializedName("community_name")
  val communityName: kotlin.String? = null,

)
