/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.ModAdd
import com.idunnololz.summit.api.dto.piefed.models.Person

/**
 *
 *
 * @param modAdd
 * @param moderator
 * @param moddedPerson
 */

data class ModAddView(

  @SerializedName("mod_add")
  val modAdd: ModAdd,

  @SerializedName("moderator")
  val moderator: Person? = null,

  @SerializedName("modded_person")
  val moddedPerson: Person? = null,

)
