/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.Community
import com.idunnololz.summit.api.dto.piefed.models.ModAddCommunity
import com.idunnololz.summit.api.dto.piefed.models.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param modAddCommunity 
 * @param moderator 
 * @param community 
 * @param moddedPerson 
 */


data class ModAddCommunityView (

    @SerializedName("mod_add_community")
    val modAddCommunity: ModAddCommunity,

    @SerializedName("moderator")
    val moderator: Person? = null,

    @SerializedName("community")
    val community: Community? = null,

    @SerializedName("modded_person")
    val moddedPerson: Person? = null

) {


}

