/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.Community
import com.idunnololz.summit.api.dto.piefed.models.ModBanFromCommunity
import com.idunnololz.summit.api.dto.piefed.models.Person

/**
 *
 *
 * @param modBanFromCommunity
 * @param moderator
 * @param community
 * @param bannedPerson
 */

data class ModBanFromCommunityView(

  @SerializedName("mod_ban_from_community")
  val modBanFromCommunity: ModBanFromCommunity,

  @SerializedName("moderator")
  val moderator: Person? = null,

  @SerializedName("community")
  val community: Community? = null,

  @SerializedName("banned_person")
  val bannedPerson: Person? = null,

)
