/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.Community
import com.idunnololz.summit.api.dto.piefed.models.ModFeaturePost
import com.idunnololz.summit.api.dto.piefed.models.Person
import com.idunnololz.summit.api.dto.piefed.models.Post

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param modFeaturePost 
 * @param moderator 
 * @param post 
 * @param community 
 */


data class ModFeaturePostView (

    @SerializedName("mod_feature_post")
    val modFeaturePost: ModFeaturePost,

    @SerializedName("moderator")
    val moderator: Person? = null,

    @SerializedName("post")
    val post: Post? = null,

    @SerializedName("community")
    val community: Community? = null

) {


}

