/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.Community
import com.idunnololz.summit.api.dto.piefed.models.ModHideCommunity
import com.idunnololz.summit.api.dto.piefed.models.Person

/**
 *
 *
 * @param modHideCommunity
 * @param community
 * @param admin
 */

data class ModHideCommunityView(

  @SerializedName("mod_hide_community")
  val modHideCommunity: ModHideCommunity,

  @SerializedName("community")
  val community: Community,

  @SerializedName("admin")
  val admin: Person? = null,

)
