/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param modPersonId
 * @param postId
 * @param locked
 * @param `when`
 */

data class ModLockPost(

  @SerializedName("id")
  val id: kotlin.Int,

  @SerializedName("mod_person_id")
  val modPersonId: kotlin.Int?,

  @SerializedName("post_id")
  val postId: kotlin.Int?,

  @SerializedName("locked")
  val locked: kotlin.Boolean,

  @SerializedName("when_")
  val `when`: kotlin.String,

)
