/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.Community
import com.idunnololz.summit.api.dto.piefed.models.ModRemoveCommunity
import com.idunnololz.summit.api.dto.piefed.models.Person

/**
 *
 *
 * @param modRemoveCommunity
 * @param moderator
 * @param community
 */

data class ModRemoveCommunityView(

  @SerializedName("mod_remove_community")
  val modRemoveCommunity: ModRemoveCommunity,

  @SerializedName("moderator")
  val moderator: Person? = null,

  @SerializedName("community")
  val community: Community? = null,

)
