/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.UserExtraField

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param actorId 
 * @param banned 
 * @param bot 
 * @param deleted 
 * @param id 
 * @param instanceId 
 * @param local 
 * @param userName 
 * @param about 
 * @param aboutHtml 
 * @param avatar 
 * @param banner 
 * @param extraFields 
 * @param note 
 * @param flair 
 * @param published 
 * @param title 
 */


data class Person (

    @SerializedName("actor_id")
    val actorId: kotlin.String,

    @SerializedName("banned")
    val banned: kotlin.Boolean,

    @SerializedName("bot")
    val bot: kotlin.Boolean,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("instance_id")
    val instanceId: kotlin.Int,

    @SerializedName("local")
    val local: kotlin.Boolean,

    @SerializedName("user_name")
    val userName: kotlin.String,

    @SerializedName("about")
    val about: kotlin.String? = null,

    @SerializedName("about_html")
    val aboutHtml: kotlin.String? = null,

    @SerializedName("avatar")
    val avatar: kotlin.String? = null,

    @SerializedName("banner")
    val banner: kotlin.String? = null,

    @SerializedName("extra_fields")
    val extraFields: kotlin.collections.List<UserExtraField>? = null,

    @SerializedName("note")
    val note: kotlin.String? = null,

    @SerializedName("flair")
    val flair: kotlin.String? = null,

    @SerializedName("published")
    val published: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null

) {


}

