/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param comments
 * @param downvotes
 * @param newestCommentTime
 * @param postId
 * @param published
 * @param score
 * @param upvotes
 * @param crossPosts
 */

data class PostAggregates(

  @SerializedName("comments")
  val comments: kotlin.Int,

  @SerializedName("downvotes")
  val downvotes: kotlin.Int,

  @SerializedName("newest_comment_time")
  val newestCommentTime: kotlin.String,

  @SerializedName("post_id")
  val postId: kotlin.Int,

  @SerializedName("published")
  val published: kotlin.String,

  @SerializedName("score")
  val score: kotlin.Int,

  @SerializedName("upvotes")
  val upvotes: kotlin.Int,

  @SerializedName("cross_posts")
  val crossPosts: kotlin.Int,

)
