/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.piefed.models.Person
import com.idunnololz.summit.api.dto.piefed.models.PrivateMessage
import com.idunnololz.summit.api.dto.piefed.models.PrivateMessageReport

/**
 *
 *
 * @param privateMessageReport
 * @param privateMessage
 * @param privateMessageCreator
 * @param creator
 */

data class PrivateMessageReportView(

  @SerializedName("private_message_report")
  val privateMessageReport: PrivateMessageReport? = null,

  @SerializedName("private_message")
  val privateMessage: PrivateMessage? = null,

  @SerializedName("private_message_creator")
  val privateMessageCreator: Person? = null,

  @SerializedName("creator")
  val creator: Person? = null,

)
