/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param postId
 * @param removed
 * @param reason
 */

data class RemovePostRequest(

  @SerializedName("post_id")
  val postId: kotlin.Int,

  @SerializedName("removed")
  val removed: kotlin.Boolean,

  @SerializedName("reason")
  val reason: kotlin.String? = null,

)
