/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param commentId
 * @param reason
 * @param description
 * @param reportRemote Also send report to originating instance
 */

data class ReportCommentRequest(

  @SerializedName("comment_id")
  val commentId: kotlin.Int,

  @SerializedName("reason")
  val reason: kotlin.String,

  @SerializedName("description")
  val description: kotlin.String? = null,

  /* Also send report to originating instance */
  @SerializedName("report_remote")
  val reportRemote: kotlin.Boolean? = true,

)
