/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.CommentReplyView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param replies 
 * @param nextPage 
 */


data class UserMentionsResponse (

    @SerializedName("replies")
    val replies: kotlin.collections.List<CommentReplyView>,

    @SerializedName("next_page")
    val nextPage: kotlin.String? = null

) {


}

