/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models

import com.idunnololz.summit.api.dto.piefed.models.CommentReplyView

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param replies Should be empty list
 */


data class UserMarkAllReadResponse (

    /* Should be empty list */
    @SerializedName("replies")
    val replies: kotlin.collections.List<CommentReplyView>

) {


}

