/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param personId
 * @param subscribe
 */

data class UserSubscribeRequest(

  @SerializedName("person_id")
  val personId: kotlin.Int,

  @SerializedName("subscribe")
  val subscribe: kotlin.Boolean,

)
