/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param label 
 * @param text 
 */


data class UserExtraField (

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("label")
    val label: kotlin.String,

    @SerializedName("text")
    val text: kotlin.String

) {


}

