/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.piefed.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notifId 
 * @param readState true sets notification as read, false marks it unread
 */


data class UserNotificationStateRequest (

    @SerializedName("notif_id")
    val notifId: kotlin.Int,

    /* true sets notification as read, false marks it unread */
    @SerializedName("read_state")
    val readState: kotlin.Boolean

) {


}

