/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.piefed.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param username
 * @param password
 * @param passwordVerify
 * @param showNsfw
 * @param email
 * @param captchaUuid
 * @param captchaAnswer
 * @param honeypot
 * @param answer
 */

data class UserRegistrationRequest(

  @SerializedName("username")
  val username: kotlin.String,

  @SerializedName("password")
  val password: kotlin.String,

  @SerializedName("password_verify")
  val passwordVerify: kotlin.String,

  @SerializedName("show_nsfw")
  val showNsfw: kotlin.Boolean? = null,

  @SerializedName("email")
  val email: kotlin.String? = null,

  @SerializedName("captcha_uuid")
  val captchaUuid: kotlin.String? = null,

  @SerializedName("captcha_answer")
  val captchaAnswer: kotlin.String? = null,

  @SerializedName("honeypot")
  val honeypot: kotlin.String? = null,

  @SerializedName("answer")
  val answer: kotlin.String? = null,

)
