/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.PersonView

import com.google.gson.annotations.SerializedName

/**
 * The response of current admins.
 *
 * @param admins 
 */


data class AddAdminResponse (

    @SerializedName("admins")
    val admins: kotlin.collections.List<PersonView>

) {


}

