/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Adds an admin to a site.
 *
 * @param added
 * @param personId The person id.
 */

data class AddAdmin(

  @SerializedName("added")
  val added: kotlin.Boolean,

  /* The person id. */
  @SerializedName("person_id")
  val personId: kotlin.Long,

)
