/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param reason 
 * @param allow 
 * @param instance 
 */


data class AdminAllowInstanceParams (

    @SerializedName("reason")
    val reason: kotlin.String,

    @SerializedName("allow")
    val allow: kotlin.Boolean,

    @SerializedName("instance")
    val instance: kotlin.String

) {


}

