/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Approves a registration application.
 *
 * @param approve 
 * @param id The registration application id.
 * @param denyReason 
 */


data class ApproveRegistrationApplication (

    @SerializedName("approve")
    val approve: kotlin.Boolean,

    /* The registration application id. */
    @SerializedName("id")
    val id: kotlin.Double,

    @SerializedName("deny_reason")
    val denyReason: kotlin.String? = null

) {


}

