/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Ban a person from the site.
 *
 * @param reason 
 * @param ban 
 * @param personId The person id.
 * @param expiresAt A time that the ban will expire, in unix epoch seconds.  An i64 unix timestamp is used for a simpler API client implementation.
 * @param removeOrRestoreData Optionally remove or restore all their data. Useful for new troll accounts. If ban is true, then this means remove. If ban is false, it means restore.
 */


data class BanPerson (

    @SerializedName("reason")
    val reason: kotlin.String,

    @SerializedName("ban")
    val ban: kotlin.Boolean,

    /* The person id. */
    @SerializedName("person_id")
    val personId: kotlin.Long,

    /* A time that the ban will expire, in unix epoch seconds.  An i64 unix timestamp is used for a simpler API client implementation. */
    @SerializedName("expires_at")
    val expiresAt: kotlin.Long? = null,

    /* Optionally remove or restore all their data. Useful for new troll accounts. If ban is true, then this means remove. If ban is false, it means restore. */
    @SerializedName("remove_or_restore_data")
    val removeOrRestoreData: kotlin.Boolean? = null

) {


}

