/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Defines who can browse and interact with content in a community.
 *
 * Values: `public`,unlisted,local_only_public,local_only_private,`private`
 */

enum class CommunityVisibility(
  val value: kotlin.String,
) {

  @SerializedName(value = "public")
  `public`("public"),

  @SerializedName(value = "unlisted")
  unlisted("unlisted"),

  @SerializedName(value = "local_only_public")
  local_only_public("local_only_public"),

  @SerializedName(value = "local_only_private")
  local_only_private("local_only_private"),

  @SerializedName(value = "private")
  `private`("private"),
  ;

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use
   * the actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that
   * the client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /**
     * Converts the provided [data] to a [String] on success, null otherwise.
     */
    fun encode(data: kotlin.Any?): kotlin.String? =
      if (data is CommunityVisibility) "$data" else null

    /**
     * Returns a valid [CommunityVisibility] for [data], null otherwise.
     */
    fun decode(data: kotlin.Any?): CommunityVisibility? = data?.let {
      val normalizedData = "$it".lowercase()
      values().firstOrNull { value ->
        it == value || normalizedData == "$value".lowercase()
      }
    }
  }
}
