/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.Community
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityReport
import com.idunnololz.summit.api.dto.lemmy.v4.models.Person

import com.google.gson.annotations.SerializedName

/**
 * A community report view.
 *
 * @param creatorBannedFromCommunity 
 * @param creatorBanned 
 * @param creatorIsModerator 
 * @param creatorIsAdmin 
 * @param creator 
 * @param community 
 * @param communityReport 
 * @param creatorCommunityBanExpiresAt 
 * @param creatorBanExpiresAt 
 * @param resolver 
 */


data class CommunityReportView (

    @SerializedName("creator_banned_from_community")
    val creatorBannedFromCommunity: kotlin.Boolean,

    @SerializedName("creator_banned")
    val creatorBanned: kotlin.Boolean,

    @SerializedName("creator_is_moderator")
    val creatorIsModerator: kotlin.Boolean,

    @SerializedName("creator_is_admin")
    val creatorIsAdmin: kotlin.Boolean,

    @SerializedName("creator")
    val creator: Person,

    @SerializedName("community")
    val community: Community,

    @SerializedName("community_report")
    val communityReport: CommunityReport,

    @SerializedName("creator_community_ban_expires_at")
    val creatorCommunityBanExpiresAt: kotlin.String? = null,

    @SerializedName("creator_ban_expires_at")
    val creatorBanExpiresAt: kotlin.String? = null,

    @SerializedName("resolver")
    val resolver: Person? = null

) {


}

