/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.TagColor

import com.google.gson.annotations.SerializedName

/**
 * A tag that is created by community moderators, and assigned to posts by the creator or by mods.
 *
 * @param color 
 * @param deleted 
 * @param publishedAt 
 * @param communityId The community id.
 * @param name 
 * @param apId 
 * @param id The community tag id
 * @param updatedAt 
 * @param summary 
 * @param displayName 
 */


data class CommunityTag (

    @SerializedName("color")
    val color: TagColor,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean,

    @SerializedName("published_at")
    val publishedAt: kotlin.String,

    /* The community id. */
    @SerializedName("community_id")
    val communityId: kotlin.Double,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("ap_id")
    val apId: kotlin.String,

    /* The community tag id */
    @SerializedName("id")
    val id: kotlin.Double,

    @SerializedName("updated_at")
    val updatedAt: kotlin.String? = null,

    @SerializedName("summary")
    val summary: kotlin.String? = null,

    @SerializedName("display_name")
    val displayName: kotlin.String? = null

) {


}

