/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityReportView

import com.google.gson.annotations.SerializedName

/**
 * A community report response.
 *
 * @param communityReportView 
 */


data class CommunityReportResponse (

    @SerializedName("community_report_view")
    val communityReportView: CommunityReportView

) {


}

