/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.Community
import com.idunnololz.summit.api.dto.lemmy.v4.models.Person

/**
 * A community follower.
 *
 * @param follower
 * @param community
 */

data class CommunityFollowerView(

  @SerializedName("follower")
  val follower: Person,

  @SerializedName("community")
  val community: Community,

)
