/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Create a report for a community.
 *
 * @param reason 
 * @param communityId The community id.
 */


data class CreateCommunityReport (

    @SerializedName("reason")
    val reason: kotlin.String,

    /* The community id. */
    @SerializedName("community_id")
    val communityId: kotlin.Int

) {


}

