/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommentSortType
import com.idunnololz.summit.api.dto.lemmy.v4.models.FederationMode
import com.idunnololz.summit.api.dto.lemmy.v4.models.ImageMode
import com.idunnololz.summit.api.dto.lemmy.v4.models.ListingType
import com.idunnololz.summit.api.dto.lemmy.v4.models.PostListingMode
import com.idunnololz.summit.api.dto.lemmy.v4.models.PostSortType
import com.idunnololz.summit.api.dto.lemmy.v4.models.RegistrationMode

/**
 * Creates a site. Should be done after first running lemmy.
 *
 * @param name
 * @param maxInvitesPerUserAllowed
 * @param imageUploadDisabled
 * @param imageAllowVideoUploads
 * @param imageMaxUploadSize
 * @param imageMaxBannerSize
 * @param imageMaxAvatarSize
 * @param imageMaxThumbnailSize
 * @param imageUploadTimeoutSeconds
 * @param imageProxyBypassDomains
 * @param imageMode
 * @param suggestedMultiCommunityId
 * @param emailNotificationsDisabled
 * @param nsfwContentDisallowed
 * @param commentDownvotes
 * @param commentUpvotes
 * @param postDownvotes
 * @param postUpvotes
 * @param federationSignedFetch
 * @param reportsEmailAdmins
 * @param contentWarning
 * @param oauthRegistration
 * @param registrationMode
 * @param federationEnabled
 * @param rateLimitImportUserSettingsIntervalSeconds
 * @param rateLimitImportUserSettingsMaxRequests
 * @param rateLimitSearchIntervalSeconds
 * @param rateLimitSearchMaxRequests
 * @param rateLimitCommentIntervalSeconds
 * @param rateLimitCommentMaxRequests
 * @param rateLimitImageIntervalSeconds
 * @param rateLimitImageMaxRequests
 * @param rateLimitRegisterIntervalSeconds
 * @param rateLimitRegisterMaxRequests
 * @param rateLimitPostIntervalSeconds
 * @param rateLimitPostMaxRequests
 * @param rateLimitMessageIntervalSeconds
 * @param rateLimitMessageMaxRequests
 * @param slurFilterRegex
 * @param discussionLanguages
 * @param applicationEmailAdmins
 * @param legalInformation
 * @param defaultCommentSortType
 * @param defaultItemsPerPage
 * @param defaultPostTimeRangeSeconds
 * @param defaultPostSortType
 * @param defaultPostListingMode
 * @param defaultPostListingType
 * @param defaultTheme
 * @param privateInstance
 * @param applicationQuestion
 * @param emailVerificationRequired
 * @param communityCreationAdminOnly
 * @param summary
 * @param sidebar
 */

data class CreateSite(

  @SerializedName("name")
  val name: kotlin.String,

  @SerializedName("max_invites_per_user_allowed")
  val maxInvitesPerUserAllowed: kotlin.Int? = null,

  @SerializedName("image_upload_disabled")
  val imageUploadDisabled: kotlin.Boolean? = null,

  @SerializedName("image_allow_video_uploads")
  val imageAllowVideoUploads: kotlin.Boolean? = null,

  @SerializedName("image_max_upload_size")
  val imageMaxUploadSize: kotlin.Int? = null,

  @SerializedName("image_max_banner_size")
  val imageMaxBannerSize: kotlin.Int? = null,

  @SerializedName("image_max_avatar_size")
  val imageMaxAvatarSize: kotlin.Int? = null,

  @SerializedName("image_max_thumbnail_size")
  val imageMaxThumbnailSize: kotlin.Int? = null,

  @SerializedName("image_upload_timeout_seconds")
  val imageUploadTimeoutSeconds: kotlin.Double? = null,

  @SerializedName("image_proxy_bypass_domains")
  val imageProxyBypassDomains: kotlin.String? = null,

  @SerializedName("image_mode")
  val imageMode: ImageMode? = null,

  @SerializedName("suggested_multi_community_id")
  val suggestedMultiCommunityId: kotlin.Double? = null,

  @SerializedName("email_notifications_disabled")
  val emailNotificationsDisabled: kotlin.Boolean? = null,

  @SerializedName("nsfw_content_disallowed")
  val nsfwContentDisallowed: kotlin.Boolean? = null,

  @SerializedName("comment_downvotes")
  val commentDownvotes: FederationMode? = null,

  @SerializedName("comment_upvotes")
  val commentUpvotes: FederationMode? = null,

  @SerializedName("post_downvotes")
  val postDownvotes: FederationMode? = null,

  @SerializedName("post_upvotes")
  val postUpvotes: FederationMode? = null,

  @SerializedName("federation_signed_fetch")
  val federationSignedFetch: kotlin.Boolean? = null,

  @SerializedName("reports_email_admins")
  val reportsEmailAdmins: kotlin.Boolean? = null,

  @SerializedName("content_warning")
  val contentWarning: kotlin.String? = null,

  @SerializedName("oauth_registration")
  val oauthRegistration: kotlin.Boolean? = null,

  @SerializedName("registration_mode")
  val registrationMode: RegistrationMode? = null,

  @SerializedName("federation_enabled")
  val federationEnabled: kotlin.Boolean? = null,

  @SerializedName("rate_limit_import_user_settings_interval_seconds")
  val rateLimitImportUserSettingsIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_import_user_settings_max_requests")
  val rateLimitImportUserSettingsMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_search_interval_seconds")
  val rateLimitSearchIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_search_max_requests")
  val rateLimitSearchMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_comment_interval_seconds")
  val rateLimitCommentIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_comment_max_requests")
  val rateLimitCommentMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_image_interval_seconds")
  val rateLimitImageIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_image_max_requests")
  val rateLimitImageMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_register_interval_seconds")
  val rateLimitRegisterIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_register_max_requests")
  val rateLimitRegisterMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_post_interval_seconds")
  val rateLimitPostIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_post_max_requests")
  val rateLimitPostMaxRequests: kotlin.Double? = null,

  @SerializedName("rate_limit_message_interval_seconds")
  val rateLimitMessageIntervalSeconds: kotlin.Double? = null,

  @SerializedName("rate_limit_message_max_requests")
  val rateLimitMessageMaxRequests: kotlin.Double? = null,

  @SerializedName("slur_filter_regex")
  val slurFilterRegex: kotlin.String? = null,

  @SerializedName("discussion_languages")
  val discussionLanguages: kotlin.collections.List<kotlin.Double>? = null,

  @SerializedName("application_email_admins")
  val applicationEmailAdmins: kotlin.Boolean? = null,

  @SerializedName("legal_information")
  val legalInformation: kotlin.String? = null,

  @SerializedName("default_comment_sort_type")
  val defaultCommentSortType: CommentSortType? = null,

  @SerializedName("default_items_per_page")
  val defaultItemsPerPage: kotlin.Double? = null,

  @SerializedName("default_post_time_range_seconds")
  val defaultPostTimeRangeSeconds: kotlin.Double? = null,

  @SerializedName("default_post_sort_type")
  val defaultPostSortType: PostSortType? = null,

  @SerializedName("default_post_listing_mode")
  val defaultPostListingMode: PostListingMode? = null,

  @SerializedName("default_post_listing_type")
  val defaultPostListingType: ListingType? = null,

  @SerializedName("default_theme")
  val defaultTheme: kotlin.String? = null,

  @SerializedName("private_instance")
  val privateInstance: kotlin.Boolean? = null,

  @SerializedName("application_question")
  val applicationQuestion: kotlin.String? = null,

  @SerializedName("email_verification_required")
  val emailVerificationRequired: kotlin.Boolean? = null,

  @SerializedName("community_creation_admin_only")
  val communityCreationAdminOnly: kotlin.Boolean? = null,

  @SerializedName("summary")
  val summary: kotlin.String? = null,

  @SerializedName("sidebar")
  val sidebar: kotlin.String? = null,

)
