/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Creates a warning against a post and notifies the user.
 *
 * @param reason 
 * @param postId The post id.
 */


data class CreatePostWarning (

    @SerializedName("reason")
    val reason: kotlin.String,

    /* The post id. */
    @SerializedName("post_id")
    val postId: kotlin.Double

) {


}

