/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Create a report for a private message.
 *
 * @param reason 
 * @param privateMessageId The private message id.
 */


data class CreatePrivateMessageReport (

    @SerializedName("reason")
    val reason: kotlin.String,

    /* The private message id. */
    @SerializedName("private_message_id")
    val privateMessageId: kotlin.Double

) {


}

