/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.LocalUserInvite

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param invite 
 */


data class CreateInvitationResponse (

    @SerializedName("invite")
    val invite: LocalUserInvite

) {


}

