/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param communityId The community id.
 * @param id
 */

data class CreateOrDeleteMultiCommunityEntry(

  /* The community id. */
  @SerializedName("community_id")
  val communityId: kotlin.Int,

  @SerializedName("id")
  val id: kotlin.Int,

)
