/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Like a comment.
 *
 * @param commentId The comment id.
 * @param isUpvote True means Upvote, False means Downvote, and None means remove vote.
 */


data class CreateCommentLike (

    /* The comment id. */
    @SerializedName("comment_id")
    val commentId: kotlin.Int,

    /* True means Upvote, False means Downvote, and None means remove vote. */
    @SerializedName("is_upvote")
    val isUpvote: kotlin.Boolean? = null

) {


}

