/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityVisibility

import com.google.gson.annotations.SerializedName

/**
 * Create a community.
 *
 * @param title A longer title.
 * @param name The unique name.
 * @param visibility 
 * @param discussionLanguages 
 * @param postingRestrictedToMods Whether to restrict posting only to moderators.
 * @param nsfw Whether its an NSFW community.
 * @param banner A banner URL.
 * @param icon An icon URL.
 * @param summary A shorter, one line summary of your community.
 * @param sidebar A sidebar for the community in markdown.
 */


data class CreateCommunity (

    /* A longer title. */
    @SerializedName("title")
    val title: kotlin.String,

    /* The unique name. */
    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("visibility")
    val visibility: CommunityVisibility? = null,

    @SerializedName("discussion_languages")
    val discussionLanguages: kotlin.collections.List<kotlin.Double>? = null,

    /* Whether to restrict posting only to moderators. */
    @SerializedName("posting_restricted_to_mods")
    val postingRestrictedToMods: kotlin.Boolean? = null,

    /* Whether its an NSFW community. */
    @SerializedName("nsfw")
    val nsfw: kotlin.Boolean? = null,

    /* A banner URL. */
    @SerializedName("banner")
    val banner: kotlin.String? = null,

    /* An icon URL. */
    @SerializedName("icon")
    val icon: kotlin.String? = null,

    /* A shorter, one line summary of your community. */
    @SerializedName("summary")
    val summary: kotlin.String? = null,

    /* A sidebar for the community in markdown. */
    @SerializedName("sidebar")
    val sidebar: kotlin.String? = null

) {


}

