/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.CustomEmoji
import com.idunnololz.summit.api.dto.lemmy.v4.models.CustomEmojiKeyword

/**
 * A custom emoji view.
 *
 * @param keywords
 * @param customEmoji
 */

data class CustomEmojiView(

  @SerializedName("keywords")
  val keywords: kotlin.collections.List<CustomEmojiKeyword>,

  @SerializedName("custom_emoji")
  val customEmoji: CustomEmoji,

)
