/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Delete an external auth method.
 *
 * @param id The oauth provider id.
 */


data class DeleteOAuthProvider (

    /* The oauth provider id. */
    @SerializedName("id")
    val id: kotlin.Double

) {


}

