/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Delete a post.
 *
 * @param deleted
 * @param postId The post id.
 */

data class DeletePost(

  @SerializedName("deleted")
  val deleted: kotlin.Boolean,

  /* The post id. */
  @SerializedName("post_id")
  val postId: kotlin.Int,

)
