/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Delete a private message.
 *
 * @param deleted
 * @param privateMessageId The private message id.
 */

data class DeletePrivateMessage(

  @SerializedName("deleted")
  val deleted: kotlin.Boolean,

  /* The private message id. */
  @SerializedName("private_message_id")
  val privateMessageId: kotlin.Int,

)
