/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Delete your own community.
 *
 * @param deleted 
 * @param communityId The community id.
 */


data class DeleteCommunity (

    @SerializedName("deleted")
    val deleted: kotlin.Boolean,

    /* The community id. */
    @SerializedName("community_id")
    val communityId: kotlin.Double

) {


}

