/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.TagColor

import com.google.gson.annotations.SerializedName

/**
 * Make changes to a community tag
 *
 * @param tagId The community tag id
 * @param color 
 * @param summary 
 * @param displayName 
 */


data class EditCommunityTag (

    /* The community tag id */
    @SerializedName("tag_id")
    val tagId: kotlin.Int,

    @SerializedName("color")
    val color: TagColor? = null,

    @SerializedName("summary")
    val summary: kotlin.String? = null,

    @SerializedName("display_name")
    val displayName: kotlin.String? = null

) {


}

