/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.PostNotificationsMode

import com.google.gson.annotations.SerializedName

/**
 * Change notification settings for a post
 *
 * @param mode 
 * @param postId The post id.
 */


data class EditPostNotifications (

    @SerializedName("mode")
    val mode: PostNotificationsMode,

    /* The post id. */
    @SerializedName("post_id")
    val postId: kotlin.Int

) {


}

