/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param enabled 
 * @param totpToken 
 */


data class EditTotp (

    @SerializedName("enabled")
    val enabled: kotlin.Boolean,

    @SerializedName("totp_token")
    val totpToken: kotlin.String

) {


}

