/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityNotificationsMode

import com.google.gson.annotations.SerializedName

/**
 * Change notification settings for a community
 *
 * @param mode 
 * @param communityId The community id.
 */


data class EditCommunityNotifications (

    @SerializedName("mode")
    val mode: CommunityNotificationsMode,

    /* The community id. */
    @SerializedName("community_id")
    val communityId: kotlin.Double

) {


}

