/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Edit a comment.
 *
 * @param commentId The comment id.
 * @param languageId The language id.
 * @param content 
 */


data class EditComment (

    /* The comment id. */
    @SerializedName("comment_id")
    val commentId: kotlin.Double,

    /* The language id. */
    @SerializedName("language_id")
    val languageId: kotlin.Double? = null,

    @SerializedName("content")
    val content: kotlin.String? = null

) {


}

