/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param state 
 */


data class EmptyRequestState (

    @SerializedName("state")
    val state: EmptyRequestState.State

) {

    /**
     * 
     *
     * Values: empty
     */
    enum class State(val value: kotlin.String) {
        @SerializedName(value = "empty") empty("empty");
    }

}

