/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param publishedAt 
 * @param updatedAt 
 */


data class FederationAllowList (

    @SerializedName("published_at")
    val publishedAt: kotlin.String,

    @SerializedName("updated_at")
    val updatedAt: kotlin.String? = null

) {


}

