/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Follow / subscribe to a community.
 *
 * @param follow
 * @param communityId The community id.
 */

data class FollowCommunity(

  @SerializedName("follow")
  val follow: kotlin.Boolean,

  /* The community id. */
  @SerializedName("community_id")
  val communityId: Int,

)
