/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param follow
 * @param multiCommunityId
 */

data class FollowMultiCommunity(

  @SerializedName("follow")
  val follow: kotlin.Boolean,

  @SerializedName("multi_community_id")
  val multiCommunityId: kotlin.Int,

)
