/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommentSortType
import com.idunnololz.summit.api.dto.lemmy.v4.models.ListingType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param searchTerm 
 * @param parentId The comment id.
 * @param postId The post id.
 * @param creatorUsername 
 * @param creatorId The person id.
 * @param communityName 
 * @param communityId The community id.
 * @param limit 
 * @param pageCursor To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions.
 * @param maxDepth 
 * @param timeRangeSeconds Filter to within a given time range, in seconds. IE 60 would give results for the past minute.
 * @param sort 
 * @param type 
 */


data class GetCommentsI (

    @SerializedName("search_term")
    val searchTerm: kotlin.String? = null,

    /* The comment id. */
    @SerializedName("parent_id")
    val parentId: Int? = null,

    /* The post id. */
    @SerializedName("post_id")
    val postId: Int? = null,

    @SerializedName("creator_username")
    val creatorUsername: kotlin.String? = null,

    /* The person id. */
    @SerializedName("creator_id")
    val creatorId: Int? = null,

    @SerializedName("community_name")
    val communityName: kotlin.String? = null,

    /* The community id. */
    @SerializedName("community_id")
    val communityId: Int? = null,

    @SerializedName("limit")
    val limit: Int? = null,

    /* To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions. */
    @SerializedName("page_cursor")
    val pageCursor: kotlin.String? = null,

    @SerializedName("max_depth")
    val maxDepth: Int? = null,

    /* Filter to within a given time range, in seconds. IE 60 would give results for the past minute. */
    @SerializedName("time_range_seconds")
    val timeRangeSeconds: Int? = null,

    @SerializedName("sort")
    val sort: CommentSortType? = null,

    @SerializedName("type_")
    val type: ListingType? = null

) {


}

