/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityView
import com.idunnololz.summit.api.dto.lemmy.v4.models.PostView

/**
 * The post response.
 *
 * @param crossPosts A list of cross-posts, or other times / communities this link has been posted to.
 * @param communityView
 * @param postView
 */

data class GetPostResponse(

  @SerializedName("moderators")
  val moderators: kotlin.collections.List<CommunityModeratorView>,

  /* A list of cross-posts, or other times / communities this link has been posted to. */
  @SerializedName("cross_posts")
  val crossPosts: kotlin.collections.List<PostView>,

  @SerializedName("community_view")
  val communityView: CommunityView,

  @SerializedName("post_view")
  val postView: PostView,

)
