/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username Example: dessalines , or dessalines@xyz.tld
 * @param personId The person id.
 */


data class GetPersonDetailsI (

    /* Example: dessalines , or dessalines@xyz.tld */
    @SerializedName("username")
    val username: kotlin.String? = null,

    /* The person id. */
    @SerializedName("person_id")
    val personId: kotlin.Double? = null

) {


}

