/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param commentId The comment id.
 * @param id The post id.
 */


data class GetPostI (

    /* The comment id. */
    @SerializedName("comment_id")
    val commentId: kotlin.Double? = null,

    /* The post id. */
    @SerializedName("id")
    val id: kotlin.Double? = null

) {


}

