/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.ListingType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param showNsfw 
 * @param type 
 */


data class GetRandomCommunityI (

    @SerializedName("show_nsfw")
    val showNsfw: kotlin.Boolean? = null,

    @SerializedName("type_")
    val type: ListingType? = null

) {


}

