/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.AdminOAuthProvider
import com.idunnololz.summit.api.dto.lemmy.v4.models.Language
import com.idunnololz.summit.api.dto.lemmy.v4.models.LocalSiteUrlBlocklist
import com.idunnololz.summit.api.dto.lemmy.v4.models.PersonView
import com.idunnololz.summit.api.dto.lemmy.v4.models.PluginMetadata
import com.idunnololz.summit.api.dto.lemmy.v4.models.PublicOAuthProvider
import com.idunnololz.summit.api.dto.lemmy.v4.models.SiteView
import com.idunnololz.summit.api.dto.lemmy.v4.models.Tagline

import com.google.gson.annotations.SerializedName

/**
 * An expanded response for a site.
 *
 * @param captchaEnabled 
 * @param activePlugins 
 * @param blockedUrls 
 * @param adminOauthProviders 
 * @param oauthProviders A list of external auth methods your site supports.
 * @param discussionLanguages 
 * @param allLanguages 
 * @param version 
 * @param admins 
 * @param siteView 
 * @param lastApplicationDurationSeconds The number of seconds between the last application published, and approved / denied time.  Useful for estimating when your application will be approved.
 * @param tagline 
 */


data class GetSiteResponse (

    @SerializedName("captcha_enabled")
    val captchaEnabled: kotlin.Boolean,

    @SerializedName("active_plugins")
    val activePlugins: kotlin.collections.List<PluginMetadata>,

    @SerializedName("blocked_urls")
    val blockedUrls: kotlin.collections.List<LocalSiteUrlBlocklist>,

    @SerializedName("admin_oauth_providers")
    val adminOauthProviders: kotlin.collections.List<AdminOAuthProvider>,

    /* A list of external auth methods your site supports. */
    @SerializedName("oauth_providers")
    val oauthProviders: kotlin.collections.List<PublicOAuthProvider>,

    @SerializedName("discussion_languages")
    val discussionLanguages: kotlin.collections.List<kotlin.Double>,

    @SerializedName("all_languages")
    val allLanguages: kotlin.collections.List<Language>,

    @SerializedName("version")
    val version: kotlin.String,

    @SerializedName("admins")
    val admins: kotlin.collections.List<PersonView>,

    @SerializedName("site_view")
    val siteView: SiteView,

    /* The number of seconds between the last application published, and approved / denied time.  Useful for estimating when your application will be approved. */
    @SerializedName("last_application_duration_seconds")
    val lastApplicationDurationSeconds: kotlin.Int? = null,

    @SerializedName("tagline")
    val tagline: Tagline? = null

) {


}

