/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.LinkMetadata

import com.google.gson.annotations.SerializedName

/**
 * The site metadata response.
 *
 * @param metadata 
 */


data class GetSiteMetadataResponse (

    @SerializedName("metadata")
    val metadata: LinkMetadata

) {


}

