/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * A mode for setting how pictrs handles images.
 *
 * Values: none,store_link_previews,proxy_all_images
 */

enum class ImageMode(
  val value: kotlin.String,
) {

  @SerializedName(value = "none")
  none("none"),

  @SerializedName(value = "store_link_previews")
  store_link_previews("store_link_previews"),

  @SerializedName(value = "proxy_all_images")
  proxy_all_images("proxy_all_images"),
  ;

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use
   * the actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that
   * the client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /**
     * Converts the provided [data] to a [String] on success, null otherwise.
     */
    fun encode(data: kotlin.Any?): kotlin.String? = if (data is ImageMode) "$data" else null

    /**
     * Returns a valid [ImageMode] for [data], null otherwise.
     */
    fun decode(data: kotlin.Any?): ImageMode? = data?.let {
      val normalizedData = "$it".lowercase()
      values().firstOrNull { value ->
        it == value || normalizedData == "$value".lowercase()
      }
    }
  }
}
