/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * A language.
 *
 * @param name 
 * @param code 
 * @param id The language id.
 */


data class Language (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("code")
    val code: kotlin.String,

    /* The language id. */
    @SerializedName("id")
    val id: kotlin.Double

) {


}

