/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * The like_type for a persons liked content.
 *
 * Values: all,liked_only,disliked_only
 */

enum class LikeType(val value: kotlin.String) {

    @SerializedName(value = "all")
    all("all"),

    @SerializedName(value = "liked_only")
    liked_only("liked_only"),

    @SerializedName(value = "disliked_only")
    disliked_only("disliked_only");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LikeType) "$data" else null

        /**
         * Returns a valid [LikeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LikeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

