/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunitySortType
import com.idunnololz.summit.api.dto.lemmy.v4.models.ListingType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param limit 
 * @param pageCursor To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions.
 * @param searchTitleOnly 
 * @param searchTerm 
 * @param multiCommunityId 
 * @param showNsfw 
 * @param timeRangeSeconds Filter to within a given time range, in seconds. IE 60 would give results for the past minute.
 * @param sort 
 * @param type 
 */


data class ListCommunitiesI (

    @SerializedName("limit")
    val limit: kotlin.Int? = null,

    /* To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions. */
    @SerializedName("page_cursor")
    val pageCursor: kotlin.String? = null,

    @SerializedName("search_title_only")
    val searchTitleOnly: kotlin.Boolean? = null,

    @SerializedName("search_term")
    val searchTerm: kotlin.String? = null,

    @SerializedName("multi_community_id")
    val multiCommunityId: kotlin.Int? = null,

    @SerializedName("show_nsfw")
    val showNsfw: kotlin.Boolean? = null,

    /* Filter to within a given time range, in seconds. IE 60 would give results for the past minute. */
    @SerializedName("time_range_seconds")
    val timeRangeSeconds: kotlin.Long? = null,

    @SerializedName("sort")
    val sort: CommunitySortType? = null,

    @SerializedName("type_")
    val type: ListingType? = null

) {


}

