/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param limit 
 * @param pageCursor To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions.
 * @param allCommunities 
 * @param unreadOnly Only shows the unapproved applications
 */


data class ListCommunityPendingFollowsI (

    @SerializedName("limit")
    val limit: kotlin.Int? = null,

    /* To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions. */
    @SerializedName("page_cursor")
    val pageCursor: kotlin.String? = null,

    @SerializedName("all_communities")
    val allCommunities: kotlin.Boolean? = null,

    /* Only shows the unapproved applications */
    @SerializedName("unread_only")
    val unreadOnly: kotlin.Boolean? = null

) {


}

