/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Mark a comment reply as read.
 *
 * @param read 
 * @param notificationId 
 */


data class MarkNotificationAsRead (

    @SerializedName("read")
    val read: kotlin.Boolean,

    @SerializedName("notification_id")
    val notificationId: kotlin.Int

) {


}

