/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * Mods can change some metadata for posts
 *
 * @param postId The post id.
 * @param tags
 * @param nsfw
 */

data class ModEditPost(

  /* The post id. */
  @SerializedName("post_id")
  val postId: kotlin.Int,

  @SerializedName("tags")
  val tags: kotlin.collections.List<kotlin.Double>? = null,

  @SerializedName("nsfw")
  val nsfw: kotlin.Boolean? = null,

)
