/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityFollowerState
import com.idunnololz.summit.api.dto.lemmy.v4.models.MultiCommunity
import com.idunnololz.summit.api.dto.lemmy.v4.models.Person

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param owner 
 * @param multi 
 * @param followState 
 */


data class MultiCommunityView (

    @SerializedName("owner")
    val owner: Person,

    @SerializedName("multi")
    val multi: MultiCommunity,

    @SerializedName("follow_state")
    val followState: CommunityFollowerState? = null

) {


}

