/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: new,old,name_asc,name_desc,communities,subscribers,subscribers_local
 */

enum class MultiCommunitySortType(val value: kotlin.String) {

    @SerializedName(value = "new")
    new("new"),

    @SerializedName(value = "old")
    old("old"),

    @SerializedName(value = "name_asc")
    name_asc("name_asc"),

    @SerializedName(value = "name_desc")
    name_desc("name_desc"),

    @SerializedName(value = "communities")
    communities("communities"),

    @SerializedName(value = "subscribers")
    subscribers("subscribers"),

    @SerializedName(value = "subscribers_local")
    subscribers_local("subscribers_local");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MultiCommunitySortType) "$data" else null

        /**
         * Returns a valid [MultiCommunitySortType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MultiCommunitySortType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

