/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.Community
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityFollowerView
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityModeratorView
import com.idunnololz.summit.api.dto.lemmy.v4.models.Instance
import com.idunnololz.summit.api.dto.lemmy.v4.models.LocalUserView
import com.idunnololz.summit.api.dto.lemmy.v4.models.MultiCommunityView
import com.idunnololz.summit.api.dto.lemmy.v4.models.Person

import com.google.gson.annotations.SerializedName

/**
 * Your user info.
 *
 * @param discussionLanguages 
 * @param keywordBlocks 
 * @param personBlocks 
 * @param instancePersonsBlocks 
 * @param instanceCommunitiesBlocks 
 * @param communityBlocks 
 * @param multiCommunityFollows 
 * @param moderates 
 * @param follows 
 * @param localUserView 
 */


data class MyUserInfo (

    @SerializedName("discussion_languages")
    val discussionLanguages: kotlin.collections.List<kotlin.Double>,

    @SerializedName("keyword_blocks")
    val keywordBlocks: kotlin.collections.List<kotlin.String>,

    @SerializedName("person_blocks")
    val personBlocks: kotlin.collections.List<Person>,

    @SerializedName("instance_persons_blocks")
    val instancePersonsBlocks: kotlin.collections.List<Instance>,

    @SerializedName("instance_communities_blocks")
    val instanceCommunitiesBlocks: kotlin.collections.List<Instance>,

    @SerializedName("community_blocks")
    val communityBlocks: kotlin.collections.List<Community>,

    @SerializedName("multi_community_follows")
    val multiCommunityFollows: kotlin.collections.List<MultiCommunityView>,

    @SerializedName("moderates")
    val moderates: kotlin.collections.List<CommunityModeratorView>,

    @SerializedName("follows")
    val follows: kotlin.collections.List<CommunityFollowerView>,

    @SerializedName("local_user_view")
    val localUserView: LocalUserView

) {


}

