/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param activeMonth 
 * @param activeHalfyear 
 * @param total 
 */


data class NodeInfoUsers (

    @SerializedName("activeMonth")
    val activeMonth: kotlin.Double? = null,

    @SerializedName("activeHalfyear")
    val activeHalfyear: kotlin.Double? = null,

    @SerializedName("total")
    val total: kotlin.Double? = null

) {


}

