/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.NodeInfoUsers

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param localComments 
 * @param localPosts 
 * @param users 
 */


data class NodeInfoUsage (

    @SerializedName("localComments")
    val localComments: kotlin.Double? = null,

    @SerializedName("localPosts")
    val localPosts: kotlin.Double? = null,

    @SerializedName("users")
    val users: NodeInfoUsers? = null

) {


}

