/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param outbound
 * @param inbound
 */

data class NodeInfoServices(

  @SerializedName("outbound")
  val outbound: kotlin.collections.List<kotlin.String>? = null,

  @SerializedName("inbound")
  val inbound: kotlin.collections.List<kotlin.String>? = null,

)
