/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.NotificationType

import com.google.gson.annotations.SerializedName

/**
 * A list of possible types for the inbox.
 *
 */


enum class NotificationTypeFilter(val value: kotlin.String) {


  @SerializedName(value = "mention")
  mention("mention"),

  @SerializedName(value = "reply")
  reply("reply"),

  @SerializedName(value = "subscribed")
  subscribed("subscribed"),

  @SerializedName(value = "private_message")
  private_message("private_message"),

  @SerializedName(value = "mod_action")
  mod_action("mod_action");

}

