/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.Notification
import com.idunnololz.summit.api.dto.lemmy.v4.models.NotificationData

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param notification 
 */


data class NotificationView (

    @SerializedName("data")
    val `data`: NotificationData,

    @SerializedName("notification")
    val notification: Notification

) {


}

