/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.LocalUserView

import com.google.gson.annotations.SerializedName

/**
 * This response contains only a single page of items. To get the next page, take the cursor string from `next_page` and pass it to the same API endpoint via `page_cursor` parameter. For going to the previous page, use `prev_page` instead.
 *
 * @param items 
 * @param prevPage To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions.
 * @param nextPage To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions.
 */


data class PagedResponseLocalUserView (

    @SerializedName("items")
    val items: kotlin.collections.List<LocalUserView>,

    /* To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions. */
    @SerializedName("prev_page")
    val prevPage: kotlin.String? = null,

    /* To get the next or previous page, pass this string unchanged as `page_cursor` in a new request to the same endpoint.  Do not attempt to parse or modify the cursor string. The format is internal and may change in minor Lemmy versions. */
    @SerializedName("next_page")
    val nextPage: kotlin.String? = null

) {


}

