/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * The person sort type.
 *
 * Values: new,old,post_score,comment_score
 */

enum class PersonSortType(val value: kotlin.String) {

    @SerializedName(value = "new")
    new("new"),

    @SerializedName(value = "old")
    old("old"),

    @SerializedName(value = "post_score")
    post_score("post_score"),

    @SerializedName(value = "comment_score")
    comment_score("comment_score");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PersonSortType) "$data" else null

        /**
         * Returns a valid [PersonSortType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PersonSortType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

