/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.Comment
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommentActions
import com.idunnololz.summit.api.dto.lemmy.v4.models.Community
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityActions
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityTag
import com.idunnololz.summit.api.dto.lemmy.v4.models.ImageDetails
import com.idunnololz.summit.api.dto.lemmy.v4.models.Person
import com.idunnololz.summit.api.dto.lemmy.v4.models.PersonActions
import com.idunnololz.summit.api.dto.lemmy.v4.models.Post
import com.idunnololz.summit.api.dto.lemmy.v4.models.PostActions
import com.idunnololz.summit.api.dto.lemmy.v4.models.ResolveObjectViewAnyOf
import com.idunnololz.summit.api.dto.lemmy.v4.models.ResolveObjectViewAnyOf1

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param creatorBannedFromCommunity 
 * @param creatorIsModerator 
 * @param creatorBanned 
 * @param canMod 
 * @param tags We wrap this in a struct so we can implement FromSqlRow<Json> for it
 * @param creatorIsAdmin 
 * @param community 
 * @param creator 
 * @param post 
 * @param comment 
 * @param creatorCommunityBanExpiresAt 
 * @param creatorBanExpiresAt 
 * @param postActions 
 * @param personActions 
 * @param communityActions 
 * @param imageDetails 
 * @param commentActions 
 */


data class PostCommentCombinedView (

    @SerializedName("type_")
    val type: PostCommentCombinedView.Type,

    @SerializedName("creator_banned_from_community")
    val creatorBannedFromCommunity: kotlin.Boolean,

    @SerializedName("creator_is_moderator")
    val creatorIsModerator: kotlin.Boolean,

    @SerializedName("creator_banned")
    val creatorBanned: kotlin.Boolean,

    @SerializedName("can_mod")
    val canMod: kotlin.Boolean,

    /* We wrap this in a struct so we can implement FromSqlRow<Json> for it */
    @SerializedName("tags")
    val tags: kotlin.collections.List<CommunityTag>,

    @SerializedName("creator_is_admin")
    val creatorIsAdmin: kotlin.Boolean,

    @SerializedName("community")
    val community: Community,

    @SerializedName("creator")
    val creator: Person,

    @SerializedName("post")
    val post: Post,

    @SerializedName("comment")
    val comment: Comment,

    @SerializedName("creator_community_ban_expires_at")
    val creatorCommunityBanExpiresAt: kotlin.String? = null,

    @SerializedName("creator_ban_expires_at")
    val creatorBanExpiresAt: kotlin.String? = null,

    @SerializedName("post_actions")
    val postActions: PostActions? = null,

    @SerializedName("person_actions")
    val personActions: PersonActions? = null,

    @SerializedName("community_actions")
    val communityActions: CommunityActions? = null,

    @SerializedName("image_details")
    val imageDetails: ImageDetails? = null,

    @SerializedName("comment_actions")
    val commentActions: CommentActions? = null

) {

    /**
     * 
     *
     * Values: comment
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "comment") comment("comment");
    }

}

