/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 * A post-view mode that changes how multiple post listings look.
 *
 * Values: list,card,small_card
 */

enum class PostListingMode(
  val value: kotlin.String,
) {

  @SerializedName(value = "list")
  list("list"),

  @SerializedName(value = "card")
  card("card"),

  @SerializedName(value = "small_card")
  small_card("small_card"),
  ;

  /**
   * Override [toString()] to avoid using the enum variable name as the value, and instead use
   * the actual value defined in the API spec file.
   *
   * This solves a problem when the variable name and its value are different, and ensures that
   * the client sends the correct enum values to the server always.
   */
  override fun toString(): kotlin.String = value

  companion object {
    /**
     * Converts the provided [data] to a [String] on success, null otherwise.
     */
    fun encode(data: kotlin.Any?): kotlin.String? = if (data is PostListingMode) "$data" else null

    /**
     * Returns a valid [PostListingMode] for [data], null otherwise.
     */
    fun decode(data: kotlin.Any?): PostListingMode? = data?.let {
      val normalizedData = "$it".lowercase()
      values().firstOrNull { value ->
        it == value || normalizedData == "$value".lowercase()
      }
    }
  }
}
