/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.PrivateMessageReportView

import com.google.gson.annotations.SerializedName

/**
 * A private message report response.
 *
 * @param privateMessageReportView 
 */


data class PrivateMessageReportResponse (

    @SerializedName("private_message_report_view")
    val privateMessageReportView: PrivateMessageReportView

) {


}

