/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.PrivateMessageView

import com.google.gson.annotations.SerializedName

/**
 * A single private message response.
 *
 * @param privateMessageView 
 */


data class PrivateMessageResponse (

    @SerializedName("private_message_view")
    val privateMessageView: PrivateMessageView

) {


}

