/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * A private message.
 *
 * @param deletedByRecipient 
 * @param removed 
 * @param local 
 * @param apId 
 * @param publishedAt 
 * @param deleted 
 * @param content 
 * @param recipientId The person id.
 * @param creatorId The person id.
 * @param id The private message id.
 * @param updatedAt 
 */


data class PrivateMessage (

    @SerializedName("deleted_by_recipient")
    val deletedByRecipient: kotlin.Boolean,

    @SerializedName("removed")
    val removed: kotlin.Boolean,

    @SerializedName("local")
    val local: kotlin.Boolean,

    @SerializedName("ap_id")
    val apId: kotlin.String,

    @SerializedName("published_at")
    val publishedAt: kotlin.String,

    @SerializedName("deleted")
    val deleted: kotlin.Boolean,

    @SerializedName("content")
    val content: kotlin.String,

    /* The person id. */
    @SerializedName("recipient_id")
    val recipientId: kotlin.Double,

    /* The person id. */
    @SerializedName("creator_id")
    val creatorId: kotlin.Double,

    /* The private message id. */
    @SerializedName("id")
    val id: kotlin.Double,

    @SerializedName("updated_at")
    val updatedAt: kotlin.String? = null

) {


}

