/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Purges a post from the database. This will delete all content attached to that post.
 *
 * @param reason 
 * @param postId The post id.
 */


data class PurgePost (

    @SerializedName("reason")
    val reason: kotlin.String,

    /* The post id. */
    @SerializedName("post_id")
    val postId: kotlin.Int

) {


}

