/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Purges a comment from the database. This will delete all content attached to that comment.
 *
 * @param reason 
 * @param commentId The comment id.
 */


data class PurgeComment (

    @SerializedName("reason")
    val reason: kotlin.String,

    /* The comment id. */
    @SerializedName("comment_id")
    val commentId: kotlin.Int

) {


}

