/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.RegistrationApplicationView

import com.google.gson.annotations.SerializedName

/**
 * The response of an action done to a registration application.
 *
 * @param registrationApplication 
 */


data class RegistrationApplicationResponse (

    @SerializedName("registration_application")
    val registrationApplication: RegistrationApplicationView

) {


}

