/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.EmptyRequestState
import com.idunnololz.summit.api.dto.lemmy.v4.models.Error
import com.idunnololz.summit.api.dto.lemmy.v4.models.FailedRequestState
import com.idunnololz.summit.api.dto.lemmy.v4.models.LoadingRequestState
import com.idunnololz.summit.api.dto.lemmy.v4.models.SuccessRequestStateUploadImageResponse
import com.idunnololz.summit.api.dto.lemmy.v4.models.UploadImageResponse

/**
 * Shows the state of an API request.  Can be empty, loading, failed, or success
 *
 * @param state
 * @param err
 * @param `data`
 */

data class RequestStateUploadImageResponse(

  @SerializedName("state")
  val state: RequestStateUploadImageResponse.State,

  @SerializedName("err")
  val err: Error,

  @SerializedName("data")
  val `data`: UploadImageResponse,

) {

  /**
   *
   *
   * Values: success
   */
  enum class State(
    val value: kotlin.String,
  ) {
    @SerializedName(value = "success")
    success("success"),
  }
}
