/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Resolve a post report (mods only).
 *
 * @param resolved 
 * @param reportId The post report id.
 */


data class ResolvePostReport (

    @SerializedName("resolved")
    val resolved: kotlin.Boolean,

    /* The post report id. */
    @SerializedName("report_id")
    val reportId: kotlin.Double

) {


}

