/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models


import com.google.gson.annotations.SerializedName

/**
 * Resolve a community report.
 *
 * @param resolved 
 * @param reportId The community report id.
 */


data class ResolveCommunityReport (

    @SerializedName("resolved")
    val resolved: kotlin.Boolean,

    /* The community report id. */
    @SerializedName("report_id")
    val reportId: kotlin.Double

) {


}

