/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param q Can be the full url, or a shortened version like: !fediverse@lemmy.ml
 */

data class ResolveObjectI(

  /* Can be the full url, or a shortened version like: !fediverse@lemmy.ml */
  @SerializedName("q")
  val q: kotlin.String,

)
