/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.CommentView
import com.idunnololz.summit.api.dto.lemmy.v4.models.CommunityView
import com.idunnololz.summit.api.dto.lemmy.v4.models.MultiCommunityView
import com.idunnololz.summit.api.dto.lemmy.v4.models.PersonView
import com.idunnololz.summit.api.dto.lemmy.v4.models.PostView
import com.idunnololz.summit.api.dto.lemmy.v4.models.ResolveObjectView

import com.google.gson.annotations.SerializedName

/**
 * The search response, containing lists of the return type possibilities
 *
 * @param multiCommunities 
 * @param persons 
 * @param communities 
 * @param posts 
 * @param comments 
 * @param nextPage 
 * @param prevPage 
 * @param resolve 
 */


data class SearchResponse (

    @SerializedName("multi_communities")
    val multiCommunities: kotlin.collections.List<MultiCommunityView>,

    @SerializedName("persons")
    val persons: kotlin.collections.List<PersonView>,

    @SerializedName("communities")
    val communities: kotlin.collections.List<CommunityView>,

    @SerializedName("posts")
    val posts: kotlin.collections.List<PostView>,

    @SerializedName("comments")
    val comments: kotlin.collections.List<CommentView>,

    @SerializedName("next_page")
    val nextPage: kotlin.String? = null,

    @SerializedName("prev_page")
    val prevPage: kotlin.String? = null,

    @SerializedName("resolve")
    val resolve: ResolveObjectView? = null

) {


}

