/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.idunnololz.summit.api.dto.lemmy.v4.models.SearchResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param state 
 */


data class SuccessRequestStateSearchResponse (

    @SerializedName("data")
    val `data`: SearchResponse,

    @SerializedName("state")
    val state: SuccessRequestStateSearchResponse.State

) {

    /**
     * 
     *
     * Values: success
     */
    enum class State(val value: kotlin.String) {
        @SerializedName(value = "success") success("success");
    }

}

