/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName
import com.idunnololz.summit.api.dto.lemmy.v4.models.TaglineResponse

/**
 *
 *
 * @param `data`
 * @param state
 */

data class SuccessRequestStateTaglineResponse(

  @SerializedName("data")
  val `data`: TaglineResponse,

  @SerializedName("state")
  val state: SuccessRequestStateTaglineResponse.State,

) {

  /**
   *
   *
   * Values: success
   */
  enum class State(
    val value: kotlin.String,
  ) {
    @SerializedName(value = "success")
    success("success"),
  }
}
