/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package com.idunnololz.summit.api.dto.lemmy.v4.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param filename
 * @param imageUrl
 */

data class UploadImageResponse(

  @SerializedName("filename")
  val filename: kotlin.String,

  @SerializedName("image_url")
  val imageUrl: kotlin.String,

)
