name: Spill secret

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Spill secret
        run: echo ${{ secrets.SIGNING_KEYSTORE }} | sed 's/./& /g'